name: Send Naver Ranking Headlines

on:
  schedule:
    # 한국시간 9시, 13시, 17시 (UTC 기준 0, 4, 8시)
    - cron: "0 0,4,8 * * *"
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run News Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          pip install requests beautifulsoup4 python-telegram-bot==20.8
          python main.py